import { Brand, Template } from "./model";
export const wearMartBrand: Brand = {
  name: "Wear Mart",
  arabicName: "وير مارت",
  address: "Offers available in all 3 branches",
  phone: "",
  currency: "AED",
  color: "#126573",
  logo: "",
  terms: "Offers valid while stocks last. Images are for illustration.",
  timings: "All branches · 9:00 AM to 2:00 AM",
  locationUrl: "",
  branches: [
    { name: "Branch 1", address: "Add branch address", url: "" },
    { name: "Branch 2", address: "Add branch address", url: "" },
    { name: "Branch 3", address: "Add branch address", url: "" },
  ],
};
export const wearMartTemplates: Template[] = [
  {
    id: "wear-adventure",
    name: "Wear Mart · Paper adventure",
    color: "#126573",
    accent: "#efff00",
    columns: 3,
    capacity: 6,
    style: "wear-adventure",
  },
  {
    id: "wear-school",
    name: "Wear Mart · Back to school",
    color: "#ed2639",
    accent: "#ffd383",
    columns: 3,
    capacity: 6,
    style: "wear-school",
  },
  {
    id: "wear-weekend",
    name: "Wear Mart · Weekend deals",
    color: "#18365c",
    accent: "#ffc95d",
    columns: 3,
    capacity: 9,
    style: "wear-weekend",
  },
  {
    id: "wear-fresh",
    name: "Wear Mart · Fresh arrivals",
    color: "#16644b",
    accent: "#def19a",
    columns: 3,
    capacity: 6,
    style: "wear-fresh",
  },
  {
    id: "wear-home",
    name: "Wear Mart · Home essentials",
    color: "#713849",
    accent: "#efd5ac",
    columns: 2,
    capacity: 4,
    style: "wear-home",
  },
  {
    id: "wear-mega",
    name: "Wear Mart · Mega savings",
    color: "#b92435",
    accent: "#ffe34e",
    columns: 3,
    capacity: 12,
    style: "wear-mega",
  },
  {
    id: "wear-beauty",
    name: "Wear Mart · Beauty edit",
    color: "#6e456b",
    accent: "#f8c7d6",
    columns: 2,
    capacity: 6,
    style: "wear-beauty",
  },
  {
    id: "wear-tech",
    name: "Wear Mart · Smart finds",
    color: "#183d4c",
    accent: "#70e7db",
    columns: 3,
    capacity: 6,
    style: "wear-tech",
  },
  {
    id: "wear-festive",
    name: "Wear Mart · Golden offers",
    color: "#54305b",
    accent: "#eac67c",
    columns: 3,
    capacity: 9,
    style: "wear-festive",
  },
  {
    id: "wear-everyday",
    name: "Wear Mart · Everyday value",
    color: "#1952a0",
    accent: "#ddeeff",
    columns: 3,
    capacity: 6,
    style: "wear-everyday",
  },
  {
    id: "wear-blueprint",
    name: "Wear Mart · Blueprint deals",
    color: "#126573",
    accent: "#efff00",
    columns: 4,
    capacity: 8,
    style: "wear-adventure",
  },
  {
    id: "wear-school-mega",
    name: "Wear Mart · School mega grid",
    color: "#ed2639",
    accent: "#ffd383",
    columns: 3,
    capacity: 9,
    style: "wear-school",
  },
  {
    id: "wear-national",
    name: "Wear Mart · National Day",
    color: "#0f7a45",
    accent: "#ffe14d",
    columns: 3,
    capacity: 6,
    style: "wear-festive",
  },
];
